config/routes.rb
Rails3::Application.routes.draw do
  root :to => "dashboard#index"

  devise_for  :users,
              :controllers => { :sessions => "user_sessions" },
              :path_names =>  { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles,:sclasses,:courses,:chapters,:cexams,:questions,:problems,:announcements,:authentications
  resources :scourses,:tcourses
  
  match '/auth/:provider/callback' => 'authentications#create', :as => :auth_callback
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }

  resources :users do
     member do
       get :edit_password 
       get :set_login
       put :update_login
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }

    resources :announcements
    resources :commits
    resources :delayed_jobs, :only => [:index]
    resources :settings 
    
    resources :users do 
      member do 
        put :operate
        put :reset_password
        put :update_password
        get :set_user_login
        get :set_user_email
        post :addrole
        delete :removerole
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :search
        get :filter
      end
    end
    
    resources :roles do
      member do 
        post :adduser
        delete :removeuser
	  end 
  	end

    resources :orgs do
      collection do
        get  :edit_school
        post :update_school
      end

    end

    resources :grades
    
    resources :sclasses do
      member do
		put  :operate
        post :add_student
        post :add_teacher
	  end 
    end
  end

  namespace :ipad do 
    root :to => 'dashboard#index'
    resources :scourses, :tcourses
  end  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  validate :name, :presence => true, :on => :create, :message => "can't be blank"
  
  def self.admin
    @@admin ||= find_by_name("admin")
  end
  
  def self.student
    @@student ||= find_by_name("student")
  end
  
  def add_user(user) 
      users << user
  end 
  
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::BaseController  
  respond_to :html, :xml, :mobile	
	
  def index
	@roles= Role.all
	@role= Role.new
    respond_with(@roles, @role)
  end
  
  def show
  	@role=Role.find(params[:id])
    respond_with(@role)
  end

  
  # POST /admin/radusers
  def create
    @role = Role.new(params[:role])
   # debugger
    respond_to do |format|
      if @role.save
        flash[:notice] = t("admin.roles.create_success")
        format.html { redirect_to(admin_roles_url) }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end  
  
  def adduser
    user= User.find_by_login(params[:search])

    @role = Role.find(params[:id])
	
	if user
		@role.users << user 
	else
        flash[:notice] = t("User_not_found")+" : "+params[:search]
	end
	
    redirect_to admin_role_path(@role)
  end

  def removeuser

    @role = Role.find(params[:id])

	if @role.id==1 && @role.users.count==1 
        flash[:notice] = t("Last_admin")
	else
    	user= User.find(params[:user_id])
		@role.users.delete(user) if user
	end

    redirect_to admin_role_path(@role)
  end


  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    redirect_to admin_roles_path
  end
end

app/views/admin/roles/_form.html.erb
<p>
<%= f.label t("admin.roles.name") %><br />
<%= f.text_field :name %><br />

<%= f.label t("admin.roles.desc") %><br />
<%= f.text_area :description,:rows =>4,:cols=>28 %><br />

<%= f.submit t("admin.roles.create") %>
</p>

app/views/admin/roles/index.html.erb
<% content_for :header do -%>
	<%= t("admin.roles.manage") %>
<% end -%>

<% content_for :sidebar do -%>
    <h2><%= t("admin.roles.new") %></h2>
	<%= form_for(@role,:url => admin_roles_path) do |f| %>
  		<%= f.error_messages %>
		<%= render :partial => 'form', :locals => {:f => f}%>
	<% end %>

<% end -%>

<table class="index">
	<tr><th><%= t("admin.roles.name") %></th><th><%= t("admin.roles.desc") %></th><th><%= t("admin.roles.rights") %></th><th align="right"></th></tr>
	<% @roles.each do |item| %>
	<tr>
		<td class="text"><%= item.name %></td>
		<td class="text"><%= item.description %></td>
		<td class="text"></td>
    	<td align=right>
    	<%= link_to(t("g.delete"),admin_role_path(item), :confirm => t("phrase.are_you_sure"), :method => :delete) unless item.id==1 %> | 
    	<%= link_to(t("admin.roles.rights"),admin_role_path(item)) %> | 
    	<%= link_to(t("admin.roles.users"),admin_role_path(item)) %>
    	</td>
	</tr>
	<% end %>
</table>	

app/views/admin/roles/show.html.erb
<% content_for :header do -%>
	<em>[<%=h @role.name %>] </em><%= t("admin.roles.members") %> 
<% end -%>

<% content_for :sidebar do -%>
   <h2><%= t("admin.roles.adduser") %></h2>
   <ul><li>
    <%= form_tag(adduser_admin_role_path) do %>
	<%= hidden_field_tag(:id, @role.id ) %>
	<%= label_tag(:search, "用户名称:") %><br />
	<%= text_field_tag(:search) %><br /><br />
	<%= submit_tag(t("g.add")) %>
    <% end %>
    </li></ul>
<% end -%>

<% ulist = @role.users %>
<% if ulist.count>0 %>
	<%=raw ulist.collect{|item| link_to(item.login, removeuser_admin_role_path(@role,:user_id=>item), :confirm => t("phrase.are_you_sure"), :method => :delete)} %>
	<br>(<%= t("admin.roles.click_remove") %>)
<% else %>
	<p><%= t("admin.roles.no_members") %></p>	

<% end %>

<hr><%= link_to t("g.back"), admin_roles_path %>