config/routes.rb
Rails3::Application.routes.draw do
  root :to => "dashboard#index"

  devise_for  :users,
              :controllers => { :sessions => "user_sessions" },
              :path_names =>  { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles,:sclasses,:courses,:chapters,:cexams,:questions,:problems,:announcements,:authentications
  resources :scourses,:tcourses
  
  match '/auth/:provider/callback' => 'authentications#create', :as => :auth_callback
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }

  resources :users do
     member do
       get :edit_password 
       get :set_login
       put :update_login
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }

    resources :announcements
    resources :commits
    resources :delayed_jobs, :only => [:index]
    resources :settings 
    
    resources :users do 
      member do 
        put :operate
        put :reset_password
        put :update_password
        get :set_user_login
        get :set_user_email
        post :addrole
        delete :removerole
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :search
        get :filter
      end
    end
    
    resources :roles do
      member do 
        post :adduser
        delete :removeuser
	  end 
  	end

    resources :orgs do
      collection do
        get  :edit_school
        post :update_school
      end

    end

    resources :grades
    
    resources :sclasses do
      member do
		put  :operate
        post :add_student
        post :add_teacher
	  end 
    end
  end

  namespace :ipad do 
    root :to => 'dashboard#index'
    resources :scourses, :tcourses
  end  
end

app/controllers/admin/sclasses_controller.rb
class  Admin::SclassesController < Admin::BaseController

  #require role
  
  def index

  end
  
  def show
    @sclass   = Sclass.find(params[:id])
    @student  = User.new
    @teacher  = User.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sclass }
    end
  end
  
  def edit
    @sclass = Sclass.find(params[:id])
  end
  
  def create
    @sclass = Sclass.new(params[:sclass])

    respond_to do |format|
      if @sclass.save
        format.html { redirect_to admin_orgs_url, notice: t('admin.orgs.create_class_success')}
        #format.json { render json: @grade, status: :created, location: @grade }
      else
        format.html { render action: "new" }
        #format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end
  
    # PUT /grades/1
  # PUT /grades/1.json
  def update
    @sclass = Sclass.find(params[:id])

    respond_to do |format|
      if @sclass.update_attributes(params[:sclass])
        format.html { redirect_to admin_orgs_url, notice: t('admin.orgs.update_class_success') }
        format.json { head :ok }
      else
        format.html { render action: "edit_class" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def add_student
    @sclass= Sclass.find(params[:id])

    @student = User.find_by_login(params[:user][:login])
    if @student.nil?
      params[:user][:password]="hello123"
      params[:user][:password_confirmation]="hello123"
      params[:user][:language]="cn"
      params[:user][:email]=params[:user][:login]+"@yucai.cn"
      
      @student = User.new(params[:user])
    end

    respond_to do |format|
      if @student.save
        logger.debug 'save student info'
        @sclass.add_student(@student)
        format.html { redirect_to admin_sclass_url(@sclass), notice: t('admin.orgs.add_student_success')}
        #format.json { render json: @grade, status: :created, location: @grade }
      else
        logger.debug 'save student false'
        format.html { redirect_to admin_sclass_url(@sclass), notice: t('admin.orgs.add_student_false')}
        #format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def add_teacher
    @sclass= Sclass.find(params[:id])

    @teacher = User.find_by_login(params[:user][:login])
    if @teacher.nil?
      params[:user][:password]="hello123"
      params[:user][:password_confirmation]="hello123"
      params[:user][:language]="cn"
      params[:user][:email]=params[:user][:login]+"@yucai.cn"
      
      @teacher = User.new(params[:user])
    end
    
    logger.debug "teacher name  "+@teacher.name
    
#=begin
    respond_to do |format|
      if @teacher.save
        logger.debug "teacher save "+@teacher.name
        @sclass.add_teacher(@teacher)
        format.html { redirect_to admin_sclass_url(@sclass), notice: t('admin.orgs.add_teacher_success')}
        #format.json { render json: @grade, status: :created, location: @grade }
      else
        format.html { redirect_to admin_sclass_url(@sclass), notice: t('admin.orgs.add_teacher_false')}
        #format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
#=end 
  end
end

app/controllers/sclasses_controller.rb
class  SclassesController < ApplicationController

  #require role
  def index

  end
  
  def show
    @sclass   = Sclass.find(params[:id])
    @course  = Course.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sclass }
    end
  end
  
  def edit
    @sclass = Sclass.find(params[:id])
  end
  
  def create
    @sclass = Sclass.new(params[:sclass])

    respond_to do |format|
      if @sclass.save
        format.html { redirect_to admin_orgs_url, notice: t('admin.orgs.create_class_success')}
        #format.json { render json: @grade, status: :created, location: @grade }
      else
        format.html { render action: "new" }
        #format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @sclass = Sclass.find(params[:id])
    respond_to do |format|
    if params[:by]=="repair"
      @sclass.repair_users
      format.html { redirect_to admin_orgs_url, notice: t('g.o_s') }
    elsif params[:by]=="add_course1"
      course=Course.find(params[:course])
      if course 
        @sclass.add_course(course)
        format.html { redirect_to courses_url, notice: t('g.a_s') }
        format.js { render "course1" }
        #format.json { head :ok }
      else
        format.html { redirect_to courses_url, notice: t('g.a_f') }
      end
    else
      if @sclass.update_attributes(params[:sclass])
        format.html { redirect_to admin_orgs_url, notice: t('g.u_s') }
        format.json { head :ok }
      else
        format.html { render action: "edit_class" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
    end
  end
    
  def destroy
    @sclass = Sclass.find(params[:id])
    respond_to do |format|
    if params[:by]=="remove_course"
      @sclass.remove_course(params[:course_id])
      format.html { redirect_to sclass_url(@sclass), notice: t('g.r_s') }
      format.json { head :ok }
    elsif params[:by]=="remove_course1"
      @sclass.remove_course(params[:course])
      format.html { redirect_to courses_url }
      format.json { head :ok }
      format.js { render "course1" }
    elsif params[:by]=="remove_teacher"
      @sclass.remove_user(params[:user_id],1)
      format.html { redirect_to sclass_url(@sclass), notice: t('g.r_s') }
    else
    
    end
    end
  end
    
end

app/views/sclasses/_form.html.erb
<%
    stitle = @sclass.id.nil? ? stitle = t('admin.orgs.create_class'):t('admin.orgs.update_class')
-%>

<%= form_for [:admin, @sclass] do |f| %>
<%= f.error_messages %>
<table >
    <%= cell(t("g.name"), (f.text_field :name))%>
    <%= cell(t("admin.orgs.grade"),f.collection_select(:grade_id, Grade.where("id>1").order("gyear"), :id, :name)) %>
    <%= cell(t("g.desc"), (f.text_area :description, :rows =>3,:cols=>28))%>
    <%= cell("", (submit_tag stitle))%>
</table>
<% end %>

app/views/sclasses/_form_student.html.erb
<%
    stitle = @student.id.nil? ? stitle = t('admin.orgs.create_student'):t('admin.orgs.update_student')
-%>

<%= form_for [:admin, @student], :url => add_student_admin_sclass_path do |f| %>
<%= f.error_messages %>
<table >
    <%= cell(t("admin.users.lsname"), (f.text_field :login))%>
    <%= cell(t("admin.users.sname"),  (f.text_field :name))%>
    <%= cell("", (submit_tag stitle))%>
</table>
<% end %>

app/views/sclasses/_form_teacher.html.erb
<%
    stitle = @teacher.id.nil? ? stitle = t('admin.orgs.create_teacher'):t('admin.orgs.update_teacher')
-%>
<%= form_for [:admin, @teacher], :url => add_teacher_admin_sclass_path do |f| %>
<%= f.error_messages %>
<table >
    <%= cell(t("admin.users.ltname"), (f.text_field :login))%>
    <%= cell(t("admin.users.sname"), (f.text_field :name))%>
    <%= cell("", (submit_tag stitle))%>
</table>
<% end %>

app/views/sclasses/_tr_s.html.erb
<td><%= sclass.grade.name %></td>
<td><%= link_to sclass.name, sclass_path(sclass,:by=>"show_member")  %></td>
<td><%= sclass.students.count %></td>
<td><% sin=","
       for c in sclass.courses %>
         <%=raw link_to(c.title,tcourse_path(c.id,:by=>"course",:sclass=>sclass.id)) %>
         <%=raw link_to_dxr(sclass_path(sclass.id,:by=>"remove_course1",:course=>c.id)) %><br>
    <% sin+=c.id.to_s+","
       end unless sclass.courses.nil? %></td>
<td><% for c in courses
          unless sin.include?(","+c.id.to_s+",") %>
             <%= link_to(c.title,sclass_path(sclass.id,:by=>"add_course1",:course=>c.id),:method=>:put,:remote=>true ) %><br>
       <% end
       end unless current_user.courses.nil? %>
</td>

app/views/sclasses/course1.js.erb
$("#tr_s_<%= @sclass.id %>").html("<%= escape_javascript render(:partial=>"tr_s",:locals => {:courses=> current_user.courses,:sclass=>@sclass })%>");

app/views/sclasses/edit.html.erb
<% content_for :header do -%> <%= t('admin.orgs.edit_class') %> <% end -%>

<% content_for :sidebar do -%>

<% end -%>

<%= render 'form' %>

<%= link_to(t('g.back'), admin_orgs_path) %>

app/views/sclasses/index.html.erb
<% content_for :header do -%><%= t("class.admin") %><% end -%>

<% content_for :sidebar do -%>
  <h2><%= t("g.title") %></h2>
<% end -%>

<table class="index">
  <%= th([t('admin.orgs.grade'),t('class.name'),t('class.s_count'),t('class.course'),t('class.course')]) %></th>
  <% for s in current_user.sclasses %>
	<tr id="tr_s_<%=s.id %>">
	<%= render(:partial=>"tr_s",:locals => { :courses=>current_user.courses,:sclass=>s }) %>
	</tr>
  <% end %>
</table>

app/views/sclasses/show.html.erb
<% content_for :header do -%> <%= t('admin.orgs.class')%> - <%= @sclass.name %> <% end -%>

<% content_for :sidebar do -%>
   <% if @sclass.teachers.count>0 %>
   <h2><%= t("admin.orgs.teacher_list") %></h2>
   <ul><% for t in @sclass.teachers %>
      <li><%= t.username %>
		  <%= link_to_dx sclass_path(@sclass,:by=>"remove_teacher",:user_id=>teacher.user_id) if t.ltype==1 %></li>
   <% end -%></ul>
   <% end -%>

   
	<h2><%= t("course.list") %></h2>
   	<ul><% for c in @sclass.courses %>
	  	<li><%= link_to c.title,course_path(c) %>
			<%= link_to_dx sclass_path(@sclass,:by=>"remove_course",:course_id=>c.id) %></li>
 	<% end %></ul>
	
<% end -%>

<table class="index">
  <tr>
	<th><%= t('admin.users.ID')%></th>
	<th><%= t('class.student')%></th>
	<th><%= t('class.course')%></th>
	<th><%= t('g.admin')%></th>
  </tr>
  
  <% icount=@sclass.students.count
     i1=1
     i=0
  %>

  <% for s in @sclass.students %>
  <tr><td><%= s.user_id %></td>
	  <td><%= s.username %> (<%= s.user.login %>)</td>
      <td><% for c in @sclass.courses %>
	  	   <%= link_to c.title,user_path(s.user_id,:course=>c.id)  %><br>
		  <% end %>
	  </td>
      <td align=right><%= link_to t("class.score_record"),user_path(s.user_id) %></td>
  </tr>
  <% end %>
</table>

<%= link_to t('g.back'), sclasses_path %>