config/routes.rb
Rails3::Application.routes.draw do
  root :to => "dashboard#index"

  devise_for  :users,
              :controllers => { :sessions => "user_sessions" },
              :path_names =>  { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles,:sclasses,:courses,:chapters,:cexams,:questions,:problems,:announcements,:authentications
  resources :scourses,:tcourses
  
  match '/auth/:provider/callback' => 'authentications#create', :as => :auth_callback
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }

  resources :users do
     member do
       get :edit_password 
       get :set_login
       put :update_login
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }

    resources :announcements
    resources :commits
    resources :delayed_jobs, :only => [:index]
    resources :settings 
    
    resources :users do 
      member do 
        put :operate
        put :reset_password
        put :update_password
        get :set_user_login
        get :set_user_email
        post :addrole
        delete :removerole
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :search
        get :filter
      end
    end
    
    resources :roles do
      member do 
        post :adduser
        delete :removeuser
	  end 
  	end

    resources :orgs do
      collection do
        get  :edit_school
        post :update_school
      end

    end

    resources :grades
    
    resources :sclasses do
      member do
		put  :operate
        post :add_student
        post :add_teacher
	  end 
    end
  end

  namespace :ipad do 
    root :to => 'dashboard#index'
    resources :scourses, :tcourses
  end  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # GET /
  # The default dashboard
  def index
    if params[:for]=="ipad"
      redirect_to ipad_root_url 
    end
    
    if logged_in?
      if current_user.teacher?
        @course= Course.new
        render "t_dashboard"
      elsif current_user.student?
        @sclass  = current_user.sclass
        @courses = @sclass.courses
        render "s_dashboard"
      end    
    end
  end
end

app/controllers/ipad/base_controller.rb
class Ipad::BaseController < ApplicationController
  filter_access_to :all
  layout 'ipad'
end

app/controllers/ipad/dashboard_controller.rb
class Ipad::DashboardController < Ipad::BaseController
  # GET /
  # The default dashboard
  def index
    if logged_in?
      if current_user.teacher?
        @course= Course.new
        render "t_dashboard"
      elsif current_user.student?
        @sclass  = current_user.sclass
        @courses = @sclass.courses
        render "s_dashboard"
      end
    else
      render "login"
    end
  end
end

app/controllers/ipad/scourses_controller.rb
class Ipad::ScoursesController < Ipad::BaseController
  # course controller for student GET /

  def index
    respond_to do |format|
      if params[:show]=="setting"
        format.js { render "setting" }
      elsif params[:show]=="course"
        format.js { render "course" }
      elsif params[:show]=="course2"
        @sclass=current_user.sclass
        format.js { render "course2" }
      elsif params[:show]=="chapter"
        @chapter=Chapter.find(params[:chapter])
        @path_root=configatron.chapter_root+@chapter.id.to_s+"/"
        format.js { render "chapter" }
      elsif params[:show]=="cexam"
        @cexam=Cexam.find(params[:cexam])
        format.js { render "cexam" }
      end 
    end
  end
  
  def show
    @show=params[:by]
    if (@show=="gc" or @show=="vc")
      @scourse  = Mlink.one(params[:id],current_user.id,Mlink::T_CHAPTER_USER )
      @chapter = Chapter.find(@scourse.id1)
      @title = t("chapter.title")      
    elsif (@show=="ge" or @show=="ve")
      @title = t("exam.title")
      @scourse  = Mlink.one(params[:id],current_user.id,Mlink::T_CEXAM_USER )
      @cexam = Cexam.find(@scourse.id1)
    end
    
    respond_to do |format|    
      format.html  # show.html.erb
      format.json { render json: @scourse }
    end
  end
  
  def edit
    @course = Course.find(params[:id])
    
    respond_to do |format|
      format.html # edit.html.erb
    end
  end
  
  def create    
    respond_to do |format|
      if (params[:by]=="chapter")
        chapter = Chapter.find(params[:id])
        if @scourse = Mlink.create(:id1=>chapter.id,:name1=>chapter.title,:order1=>chapter.cpcode,:id2=>current_user.id,:name2=>current_user.name,:order2=>current_user.login,:ltype=>Mlink::T_CHAPTER_USER,:status=>1)
          format.html { redirect_to scourse_url(@scourse), notice: t('operate.create_success')}
          #format.json { render json: @grade, status: :created, location: @grade }
        else
          #format.html { render action: "new" }
          #format.json { render json: @grade.errors, status: :unprocessable_entity }
        end
      elsif (params[:by]=="cexam")
        cexam = Cexam.find(params[:id])
        if @scourse = Mlink.create(:id1=>cexam.id,:name1=>cexam.name,:order1=>cexam.id,:id2=>current_user.id,:name2=>current_user.name,:order2=>current_user.login,:ltype=>Mlink::T_CEXAM_USER,:status=>1)
          format.html { redirect_to scourse_url(@scourse), notice: t('operate.create_success')}
          #format.json { render json: @grade, status: :created, location: @grade }
        else
          #format.html { render action: "new" }
          #format.json { render json: @grade.errors, status: :unprocessable_entity }
        end
      
      else
    
      end
    end
  end
  
  def update
    #@course = Course.find(params[:id])
    user_id=current_user.id
    respond_to do |format|
      if params[:by]=="update_exam" #update
        cexam=Cexam.find(params[:id])
        for question in cexam.questions
          aw=params["a_"+question.id.to_s]
          #logger.debug "answer:"+answer if answer
          
          sq=Sqresult.one(user_id,question.id)
          if aw
            if aw.kind_of?(Array)
              answer=aw.map {|s| s }.join
            else
              answer=aw
            end
            
            if sq
              sq.update_attributes(:answer=>answer)
            else
              sq=Sqresult.create(:student_id=>user_id,:question_id=>question.id,:answer=>answer,:qorder=>question.qorder)
            end
          else
            sq.delete if sq
          end
        end
        
        if params[:commit]==t("g.finish")
          snotice=(cexam.finish(current_user.id))?t('g.u_s'):t('g.u_f')
          format.html { redirect_to scourses_url, notice: snotice }
        else
          format.html { redirect_to scourse_url(cexam.id,:by=>"ge"), notice: t('g.u_s') }
        end
          #format.json { head :ok }
      elsif (params[:by]=="fc") #finish chapter
        cu=Mlink.one(params[:id],current_user.id,Mlink::T_CHAPTER_USER)
        if cu && cu.update_attributes(:status=>2)
          format.html { redirect_to scourses_url, notice: t('g.o_s')}
        else
          format.html { redirect_to scourses_url, notice: t('g.o_f')}
        end
      
      elsif (params[:by]=="fe") #finish exam
        eu=Mlink.one(params[:id],current_user.id,Mlink::T_CEXAM_USER)
        if eu && eu.update_attributes(:status=>2)
          format.html { redirect_to scourses_url, notice: t('g.o_s')}
        else
          format.html { redirect_to scourses_url, notice: t('g.o_f')}
        end
      end
    end
  end
end

app/controllers/ipad/tcourses_controller.rb
class Ipad::TcoursesController <  Ipad::BaseController
  # course controller for student GET /
  
  def index
    respond_to do |format|
      if params[:show]=="setting"
        format.js { render "setting" }
      elsif params[:show]=="course"
        format.js { render "course" }
      elsif params[:show]=="course2"
        @sclass=current_user.sclass
        format.js { render "course2" }
      elsif params[:show]=="chapter"
        @chapter=Chapter.find(params[:chapter])
        @path_root=configatron.chapter_root+@chapter.id.to_s+"/"
        format.js { render "chapter" }
      elsif params[:show]=="cexam"
        @cexam=Cexam.find(params[:cexam])
        format.js { render "cexam" }
      end 
    end
  end
  
  def show
    @course = Course.find(params[:id])
    @sclass = Sclass.find(params[:sclass])
    respond_to do |format|
    case params[:show] 
      when "course"
        format.html {render "_show_course"} # respond to Ajax request
        
      when "chapter"
        @chapter = Chapter.find(params[:chapter])
        @position=1
        @image=configatron.chapter_root+@chapter.id.to_s+"/"+@position.to_s.rjust(3,'0')+".jpg"
        format.js { render "chapter" }
        
      when "nav_img"
        @chapter = Chapter.find(params[:chapter])
        @position=params[:position].to_i
        logger.debug("--------------position: #{@position}")
        if params[:direct]=="home"
          @position =1 
        elsif params[:direct]=="next"
          @position += 1
        else
          @position -= 1 if @position>1
        end 
        @image=configatron.chapter_root+@chapter.id.to_s+"/"+@position.to_s.rjust(3,'0')+".jpg"
        
        format.js { render "position" }
      when "cexam"
        @cexam = Cexam.find(params[:cexam])
        format.html {render "_show_cexam"} # respond to Ajax request
    end
    end
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/ipad/dashboard/_course.html.erb
<ul data-role="listview" data-theme="g">
<% for cp in current_user.schapters %>
	<li data-role="list-divider"><%= cp.cpcode %> - <%= cp.title %></li>
	<li><%= link_to t("class.enter_chapter"),ipad_scourses_path(:by=>"chapter",:chapter=>cp.id) %></li>
	<% for ce in cp.cexams %>
		<li><%= link_to t("class.enter_cexam")+" - "+ce.name,ipad_scourses_path(:by=>"cexam",:cexam=>ce.id) %></li>
	<% end %>
<% end %>
</ul>

app/views/ipad/dashboard/login.html.erb
<div data-role="header" data-theme="f">
		<h1><%= t('session.login_info') %></h1>
</div><!-- /header -->

<!-- start content -->
<div data-role="content" data-inset="true">		

<%= form_for resource, :url => session_path(resource_name,:for=>"ipad"), :html=>{"data-ajax"=> "false"} do |f| -%>
	<fieldset>
		
		<label for="email"><%= t('session.username') %>:</label>
		<%= f.text_field 'login' %>

		<label for="password"><%= t('session.password') %></label>
		<%= f.password_field 'password' %></p>
		
		<% if devise_mapping.rememberable? -%>
			<label for="password"><%= f.check_box :remember_me %><%= t('session.remember') %></label>
		<% end -%>

		<hr />
		<%= f.submit t('session.log_in'), "data-role"=>"button", "data-inline"=>"true", "data-theme"	=>"b"  %>
	</fieldset>
	
<% end -%>
</div>

<div data-role="footer" class="footer-docs" data-theme="c">
	<p>&copy; 2012 jQuery Foundation and other contributors</p>
</div>	
<!-- end content -->

app/views/ipad/dashboard/s_dashboard.html.erb
<div data-role="page" id="page_main" class="type-interior" data-url="page_main"> 
	<div data-role="header" data-theme="f">
		<h1><%= t("site.s_dashboard") %></h1>
		<%= link_to t('session.log_out'), destroy_user_session_path(:for=>"ipad"),  "data-icon"=>"gear", "class"=>"ui-btn-right" %>
	</div><!-- /header -->

	<div data-role="content">
		<!--/content-primary -->		
		<div class="content-primary" id="pcontent1">
			<%= render("ipad/scourses/course") %>
		</div>
		
		<!-- /menu -->
		<div class="content-secondary">
			<div data-role="collapsible" data-collapsed="true" data-theme="b" data-content-theme="d">
				<ul data-role="listview"  data-theme="c" data-dividertheme="d">
					<li data-role="list-divider"><%= t("g.start") %></li>
					<li data-theme="a"><%= link_to t("class.schapter"), ipad_scourses_path(:show=>"course"),:remote=>true %></li>
					<li><%= link_to t("class.scourse"), ipad_scourses_path(:show=>"course2"),:remote=>true %></li>
					<li><%= link_to t("g.setting"), ipad_scourses_path(:show=>"setting"),:remote=>true %></li>
				</ul>
			</div>
		</div>		
	</div>
	
	<div data-role="footer" class="footer-docs" data-theme="c">
		<p><%= configatron.site_name %></p>
	</div>		
</div>

<!-- page content -->
<div data-role="page" id="page_class" data-theme="f" data-url="page_class" >
	<!-- title -->
	<div data-role="header" data-position="fixed" id="ptitle2"></div>

	<!-- content-->
	<div data-role="content" id="pcontent2"  data-theme="f" ></div>

	<!-- footer -->
	<div data-role="footer" class="ui-bar" data-position="fixed" id="pfooter2">

	</div>		
</div>
	

app/views/ipad/dashboard/t_dashboard.html.erb
<!-- Start of first page -->
<div data-role="page" id="page_main" class="type-interior">

	<div data-role="header">
		<h1><%= t("site.t_dashboard") %></h1>
		<%= link_to t('session.log_out'), destroy_user_session_path(:for=>"ipad"),  "data-icon"=>"gear", "class"=>"ui-btn-right","data-ajax"=>"false" %>
	</div><!-- /header -->
	
	<div data-role="content" class="ui-content" role="main">
		<!--/content-primary -->		
		<div class="content-primary" id="pcontent1">
			<%= render("ipad/tcourses/course") %>
		</div>
		
		<!-- /menu -->
		<div class="content-secondary">
			<div data-role="collapsible" data-collapsed="true" data-theme="b" data-content-theme="d">
				<ul data-role="listview"  data-theme="c" data-dividertheme="d">
					<li data-role="list-divider"><%= t("g.start") %></li>
					<li data-theme="a"><%= link_to t("course.list"), ipad_tcourses_path(:show=>"course"),:remote=>true %></li>
					<li><%= link_to t("class.list"), ipad_tcourses_path(:show=>"sclass"),:remote=>true %></li>
					<li><%= link_to t("g.setting"), ipad_tcourses_path(:show=>"setting"),:remote=>true %></li>
				</ul>
			</div>
		</div>	
	</div>

	<div data-role="footer">
		<h4><%= configatron.site_name %></h4>
	</div><!-- /footer -->
</div><!-- /page -->

<!-- page content -->
<div data-role="page" id="page2" data-url="page2" data-theme="f" >
	<!-- title -->
	<div data-role="header" id="header2" data-position="fixed" >
		<%= link_to t('g.back'),"#page_main" %>
		<h1 id="ptitle2"></h1>
	</div>

	<!-- content-->
	<div data-role="content" id="pcontent2"  data-theme="f" ></div>

	<!-- footer -->
	<div data-role="footer" class="ui-bar" data-position="fixed" id="pfooter2"></div>		
</div>