config/routes.rb
Rails3::Application.routes.draw do
  root :to => "dashboard#index"

  devise_for  :users,
              :controllers => { :sessions => "user_sessions" },
              :path_names =>  { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles,:sclasses,:courses,:chapters,:cexams,:questions,:problems,:announcements,:authentications
  resources :scourses,:tcourses
  
  match '/auth/:provider/callback' => 'authentications#create', :as => :auth_callback
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }

  resources :users do
     member do
       get :edit_password 
       get :set_login
       put :update_login
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }

    resources :announcements
    resources :commits
    resources :delayed_jobs, :only => [:index]
    resources :settings 
    
    resources :users do 
      member do 
        put :operate
        put :reset_password
        put :update_password
        get :set_user_login
        get :set_user_email
        post :addrole
        delete :removerole
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :search
        get :filter
      end
    end
    
    resources :roles do
      member do 
        post :adduser
        delete :removeuser
	  end 
  	end

    resources :orgs do
      collection do
        get  :edit_school
        post :update_school
      end

    end

    resources :grades
    
    resources :sclasses do
      member do
		put  :operate
        post :add_student
        post :add_teacher
	  end 
    end
  end

  namespace :ipad do 
    root :to => 'dashboard#index'
    resources :scourses, :tcourses
  end  
end

app/models/cexam.rb
class Cexam < ActiveRecord::Base
  has_many :questions, :order=>"qorder"
  belongs_to :chapter
  validate :name, :presence => true, :on => :create, :message => "can't be blank"
  
  def course
      self.chapter.course
  end
  
  def remove_question
    
  end
  
  def user_status(user_id)
    Mlink.one(self.id,user_id,Mlink::T_CEXAM_USER)
  end
  
  def finish(user_id)
    eu=Mlink.one(self.id,user_id,Mlink::T_CEXAM_USER)
    eu.update_attributes(:status=>2) unless eu.nil?
  end 
end

app/controllers/cexams_controller.rb
class CexamsController < ApplicationController
  # GET /
  # The default dashboard
  def index
    @course  = Course.new
  end
  
  def show
    @course  = Course.find(params[:id])
    @chapter = Chapter.new(:course_id=>params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sclass }
    end
  end
  
  def edit
    @cexam   = Cexam.find(params[:id])
    @problem = Problem.new
    respond_to do |format|
      format.html # edit.html.erb
    end
  end
  
  def create
    @cexam = Cexam.new(params[:cexam])

    respond_to do |format|
      if @cexam.save
        format.html { redirect_to edit_chapter_path(@cexam.chapter), notice: t('operate.create_success')}
        #format.json { render json: @grade, status: :created, location: @grade }
      else
        #format.html { render action: "new" }
        #format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @cexam = Cexam.find(params[:id])
    respond_to do |format|
      if params[:by]=="add_problem"
        problem=Problem.find_by_pcode(params[:problem])
        if problem 
          Question.create(:problem_id=>problem.id,:pcode=>problem.pcode,:cexam_id=>@cexam.id,:qorder=>1,:score=>10)
          format.html { redirect_to edit_cexam_path(@cexam), notice: t('operate.add_success') }
          #format.json { head :ok }
        else
          format.html { redirect_to edit_cexam_path(@cexam), notice: t('operate.add_false') }
        end
      elsif params[:by]=="add_question"
        problem = Problem.new(params[:problem])
        problem.owner=current_user.id
        if problem.save
          Question.create(:problem_id=>problem.id,:pcode=>problem.pcode,:cexam_id=>@cexam.id,:qorder=>1,:score=>10)
          format.html { redirect_to edit_cexam_path(@cexam), notice: t('operate.add_success') }
          #format.json { head :ok }
        else
          format.html { redirect_to edit_cexam_path(@cexam), notice: t('operate.add_false') }
        end
      elsif params[:by]=="update_problem"
        problem = Problem.find(params[:problem_id])
        if problem.update_attributes(params[:problem])
          Question.update_all({:ptype=>problem.ptype},["problem_id=?",problem.id])
          format.html { redirect_to edit_cexam_path(@cexam), notice: t('operate.add_success') }
          #format.json { head :ok }
        else
          format.html { redirect_to edit_cexam_path(@cexam), notice: t('operate.add_false') }
        end
      else
        if @cexam.update_attributes(params[:cexam])
          format.html { redirect_to course_path(@cexam.course), notice: t('operate.update_success') }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          #format.json { render json: @course.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def destroy
    @course = Course.find(params[:id])

    respond_to do |format|
      if params[:by]=="remove_teacher"
        teacher=User.find(params[:teacher])
        @course.remove_user(teacher)
        format.html { redirect_to @course }
        format.json { head :ok }
      elsif params[:by]=="remove_class"
        sclass=Sclass.find(params[:sclass])
        @course.remove_class(sclass)
        format.html { redirect_to @course }
        format.json { head :ok }
      else
        @course.delete_users
        @course.destroy
        format.html { redirect_to root_url }
        format.json { head :ok }
      end
    end
  end 
  
  def operate
    @course = Course.find(params[:id])
    case params[:by]
    when "add_teacher"

    when "remove_teacher"
      
    else
    end
    
  end
  
  
  
end

app/views/cexams/_form.html.erb
<%
    stitle = @cexam.id.nil? ? stitle = t('exam.create'):t('exam.update')
-%>

<%= form_for @cexam do |f| %>
<%= f.error_messages %>
<%= f.hidden_field :chapter_id %>
<table >
    <%= cell(t("exam.name"), (f.text_field :name))%>
    <%= cell(t("exam.type"), (f.select(:etype, t("exam.types")))) %>
    <%= cell(t("g.desc"), (f.text_area :description,:rows=>3,:cols=>24))%>

    <%= cell("", (submit_tag stitle))%>
</table>
<% end %>

app/views/cexams/_form_question.html.erb
<%
    if @problem.id.nil?
        stitle = t('problem.create')
        by="add_question"
    else
        stitle = t('problem.update')
        by="update_problem"
    end
-%>

<%= form_for @problem,:url=>cexam_path(@cexam,:by=>by,:problem_id=>@problem.id),:method=>:put do |f| %>
<%= f.error_messages %>
<table >
    <%= cell(t("problem.code"),    (f.text_field :pcode))%>
    <%= cell(t("problem.ctype"),   (f.select(:ctype, t("course.types"))+"  "+f.select(:ptype, t("problem.types"))+"  "+f.select(:status, t("problem.stypes")))) %>
    <%= cell(t("g.title"),   (f.text_area :title,:rows=>3,:cols=>30))%>
    <%= cell(t("problem.content"), (f.text_area :content,:rows=>4,:cols=>30))%>
    <%= cell(t("problem.answer"),  (f.text_area :answer,:rows=>1,:cols=>30))%>

    <%= cell("", (submit_tag stitle))%>
</table>
<% end %>

app/views/cexams/edit.html.erb
<% content_for :header do -%> <%= t('exam.edit') %> <% end -%>

<% content_for :sidebar do -%>
   <h2><%= t("exam.question") %></h2>
   <ul>
      <li><%= render ("form_question") %></li>
      <li><%= form_tag cexam_path(:by=>"add_problem"), :method => 'put' do %>
            <%= text_field_tag "problem",nil,:placeholder=>t("exam.problem_code") %>
            <%= submit_tag t("exam.add_problem") %>
          <% end %>
      </li>
      <li><%= link_to t("problem.select"), @cexam %></li>
   </ul> 
<% end -%>

<%= render 'form' %>

<hr>
<h2><%= t("problem.list") %></h2>

<table class="index">
  <tr>
	<th><%= t('problem.code')%></th>
	<th><%= t('problem.ptype')%></th>
	<th><%= t('problem.content')%></th>
	<th><%= t('problem.score')%></th>
	<th><%= t('problem.order')%></th>
	<th><%= t('g.admin')%></th>
  </tr>
  
<% for question in @cexam.questions %>
  <tr>
    <td><%= question.problem.pcode %></td>
    <td><%= t("problem.types")[question.problem.ptype][0] %></td>
        <% title=question.problem.title.nil? ? "":(question.problem.title.gsub("\n", '<br>')+"<br>") %>
    <td><%= raw title+question.problem.content.gsub("\n", '<br>') %></td>
    <td><%= question.score %></td>
    <td><%= question.qorder %></td>
    <td align=right>
      <%= link_to t("g.edit"),edit_question_path(question) %> | 
      <%= link_to t("g.remove"),question,:method=>:delete,:confirm=>t("phrase.are_you_sure") %>
    </td>
  </tr>
<% end -%>
</table>

<%= link_to(t('g.back'), course_path(@cexam.chapter.course)) %>


app/views/cexams/index.html.erb
<% content_for :header do -%><%= t("course.list") %><% end -%>

<% content_for :sidebar do -%>	
	<h2><%= t("course.new") %></h2>
	<ul><li><%= render 'courses/form' %></li></ul>
<% end -%>


<h2><%= t("course.list") %></h2>

<table class="index">
  <tr>
	<th><%= t('course.code')%></th>
	<th><%= t('course.type')%></th>
	<th><%= t('g.name')%></th>
	<th><%= t('g.desc')%></th>
	<th><%= t('g.admin')%></th>
  </tr>

  <% for ucourse in current_user.courses %>
  <tr><td><%= ucourse.course.ccode %></td>
      <td><%= t("course.types")[ucourse.course.ctype][0] %></td>
      <td><%= link_to ucourse.coursename, course_path(ucourse.course_id) %></td>
      <td><%= ucourse.course.description %></td>
      <td align=right>
	<%= link_to t("g.edit"),edit_course_path(ucourse.course_id) %> | 
	<%= link_to t("g.delete"),course_path(ucourse.course_id),:method=>:delete,:confirm=>t("phrase.are_you_sure") %>
  </td></tr>
  <% end %>
</table>




app/views/cexams/show.html.erb
<% content_for :header do -%><%= t("course.admin") %> - <%= @course.title %> <% end -%>

<% content_for :sidebar do -%>
   <h2><%= t("chapter.new") %></h2>
   <ul><li><%= render ("chapters/form") %></li></ul>

   <h2><%= t("course.teacher") %></h2>
   <ul>
      <% for teacher in @course.teachers %>
		 <li><%= teacher.linkname %>
		 <% if teacher.ltype==1 %>
			[<%= link_to "x",course_path(@course,:by=>"remove_teacher",:teacher=>teacher.link_id),:method=>:delete,:confirm=>t("phrase.are_you_sure") %>] 	 
		 <% end -%>
		 </li>
	  <% end -%>
      <li><%= render ("form_teacher") %></li>
   </ul>    

   <h2><%= t("course.class") %></h2>
   <ul>
      <% for sclass in @course.sclasses.order("linkname") %>
		 <li><%= sclass.linkname %>
			[<%= link_to "x",course_path(@course,:by=>"remove_class",:sclass=>sclass.link_id),:method=>:delete,:confirm=>t("phrase.are_you_sure") %>] 	 
		 </li>
	  <% end -%>
      <li><%= render ("form_class") %></li>
   </li></ul>    

<% end -%>

<table class="index">
  <tr>
	<th><%= t('chapter.code')%></th>
	<th><%= t('g.title')%></th>
	<th><%= t('chapter.exam')%></th>
	<th><%= t('chapter.class1')%></th>
	<th><%= t('chapter.class2')%></th>
	<th><%= t('g.admin')%></th>
  </tr>

  <% sclasses=@course.sclasses %>
  <% for chapter in @course.chapters %>
  <% s1="0" %>
  <tr><td><%= chapter.cpcode %></td>
      <td><%= chapter.title %></td>
      <td><% for exam in chapter.exams %>
	    <%  s1+=","+sclass1.link_id.to_s %>
	    <%= link_to sclass1.linkname,chapter_path(chapter,:by=>"remove_class",:sclass=>sclass1.link_id),:method=>:put %><br>
	  <% end %> 
      </td>
      <td><% for sclass1 in chapter.sclasses %>
	    <%  s1+=","+sclass1.link_id.to_s %>
	    <%= link_to sclass1.linkname,chapter_path(chapter,:by=>"remove_class",:sclass=>sclass1.link_id),:method=>:put %><br>
	  <% end %> 
      </td>
      <td><% for sclass2 in sclasses.where(" link_id not in("+s1+")").order("linkname") %>
		  <%= link_to sclass2.linkname,chapter_path(chapter,:by=>"add_class",:sclass=>sclass2.link_id),:method=>:put %><br>
		  <% end %> 
	  </td>
      <td align=right>
	  <%= link_to t("g.edit"),edit_chapter_path(chapter) %> | 
	  <%= link_to t("g.delete"),chapter,:method=>:delete,:confirm=>t("phrase.are_you_sure") %>
  </td></tr>
  <% end %>
</table>


<%= link_to t('g.back'), root_path %> | 
<%= link_to t('g.edit'), root_path %>